### PR TITLE
Updates for V 1.5.11

### PR DESCRIPTION
**Pull request by abrolag**
Not actually ready to push out V 1.5.11 however, please look this over.
There are considerable changes here, some quite major, especially in effects (we now have a proper phaser drawing).
Please check before I add any more!

### CODE REVIEW

**Comment by ahlstromcj** [comment]
Cool. Will get to it Sunday, once the daughter and family leave to go back
to Kentucky. It's been a long 2 weeks! Grampy hasn't had much time to
exercise or write code! And work is really ramping up!

**Comment by ahlstromcj** [comment]
I checked out the merge and it looks good.  Just did a quick check, will look more closely later, but you can go ahead if you have more updates.  I'm glad you're doing this!

**Comment by ahlstromcj** [comment]
I also updated the "pack" script, it was adding the .git directory to the tarball!

**Comment by abrolag** [comment]
On Sun, 07 Apr 2019 09:56:19 -0700
"C. Ahlstrom" <notifications@github.com> wrote:

> It's been a long 2 weeks! Grampy hasn't had much time to
> exercise or write code! And work is really ramping up!

Hey, you look after yourself!
You need to make sure you live long enough to be a problem to your kids :@)

> I checked out the merge and it looks good.  Just did a quick check, will look
>  more closely later, but you can go ahead if you have more updates.  I'm glad
> you're doing this!

I'm waiting to hear back from a priority user (she's blind) as to whether she
thinks my ideas will work.

I'm also easing off from the more intensive coding for a while - it was getting
to take over, and this makes a good diversion :)

> I also updated the "pack" script, it was adding the .git directory to the tarball!

Ha! See this T shirt :)

-- 
Will J Godfrey
http://www.musically.me.uk
Say you have a poem and I have a tune.
Exchange them and we can both have a poem, a tune, and a song.

**Pull request merged**
